# What language the project is of
language: python

sudo: required
dist: xenial

# What version(s) of python to test against
python:
  - "3.7"

services:
  - postgresql

addons:
  postgresql: "10"

env:
  - DJANGO_SECRET_KEY=0ub313dv=t9v#!3_(y#^cv%xvatq!0nkmwt1n-+5m^^_q@z12b

# What command to run to install dependencies
install:
  - pip install -r requirements/test.txt
  - pip install -q coveralls

# What script to run?
script:
  - coverage run manage.py test

after_success:
  - coveralls

