# What language the project is of
language: python

sudo: required
dist: xenial

# What version(s) of python to test against
python:
  - "3.7"

services:
  - postgresql

# What command to run to install dependencies
install:
  - pip install -r requirements/testing.txt

# What script to run?
script:
  - coverage run manage.py test

